# Generated by Django 4.2.7 on 2026-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoaccount',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
