# Generated by Django 4.2.7 on 2026-02-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_zohoaccount_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoaccount',
            name='bookings_service_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zohoaccount',
            name='bookings_staff_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zohoaccount',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
