# Generated by Django 4.2.7 on 2026-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_zohoaccount_bookings_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoaccount',
            name='accounts_server',
            field=models.CharField(default='https://accounts.zoho.com', max_length=255),
        ),
    ]
