# Generated by Django 4.2.7 on 2026-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_zohoaccount_accounts_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoaccount',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=100),
        ),
    ]
